# Generated by Django 3.2.20 on 2023-08-18 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_add_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='introduce',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='自己紹介'),
        ),
    ]
