# Generated by Django 3.2.20 on 2023-08-18 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_fix_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='introduce',
            new_name='introduction',
        ),
    ]
