# Generated by Django 3.2.20 on 2023-08-18 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_fix_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='updated',
            new_name='updated_at',
        ),
    ]
